### ISSUE TITLE
Junit_alcotest.run_and_report incompatible with Alcotest_lwt.test_case

### ISSUE THREAD

**Issue by yawaramin** [Khady/ocaml-junit#3]
Alcotest v1.0.0 broke compatibility with its predecessor and changed the (effective) type of `Alcotest_lwt.test_case`, from:

```
string * Alcotest.speed_level * (unit -> unit)
```

to:

```
string * Alcotest_lwt.speed_level * (unit -> unit Lwt.t)
```

`Alcotest_lwt.speed_level` here is irrelevant because it's a polymorphic variant type so still the same, but the change from `unit` to `unit Lwt.t` means `Junit_alcotest.run_and_report`, which takes a list of `Alcotest.test_case`, is incompatible with Alcotest >=v1.

**Comment by Khady** [comment]
is it actually fixed?

**Comment by yawaramin** [comment]
No, I am working around it by using `Lwt_main.run` to eliminate the promise type in each test. In unit tests the performance concern of doing that is irrelevant anyway. So just using `Alcotest.test_case` instead of `Alcotest_lwt.test_case`.
